### ISSUE TITLE
session.setField("es5", True) is being ignored

### ISSUE THREAD

**Issue by pbakaus** [zynga/jasy#100]
In the latest version of Jasy (0.8), setting

```
session.setField("es5", True)
```

doesn't actually filter out legacy es5 classes in core. Interestingly, one can prevent the bug by looping through the (non-existing) permutations once:

```
for permutation in session.permutate():
    Console.warn("due to a Jasy 0.8 bug, we need to iterate over our only permutation to filter out classes..")
```

before calling outputManager.storeLoader.

**Comment by swernerx** [comment]
This only happens when you include es5 depending classes into the kernel. Okay, that's interesting. Do you added more classes to the list since that is supported?

**Comment by swernerx** [comment]
In most builds es5 fixes are only loaded after the kernel inside the actual "main" packages you are loading afterwards.

**Comment by swernerx** [comment]
I added a new methods to pass a permutation object with all statically configured fields to the kernel classes / resolver / compressor as well. This is really a good idea and also should fix the bug you reported.

We'll release 0.8.1 later today with that fix applied, too.
