### ISSUE TITLE
Update travis.sh to fail if any of the commands in it fails

### ISSUE THREAD

**Issue by dadicool** [zynga/jasy#111]
Currently, the travis.sh reports the exit code from the last commdn only while it should report a non-zero exit code if any of the commands fails.

This bug makes this travis build : https://travis-ci.org/#!/zynga/jasy/builds/2763569 succeed while it should fail.

Dali

**Comment by swernerx** [comment]
This was not a problem in travis.sh but in jasy-test. I fixed that in jasy10 branch. This line now echos "foo" in error cases:

 bin/jasy-test || echo "foo"

**Comment by swernerx** [comment]
Fixed with 389064ab28b79707ba4f1176fe8cc6fbe4fe70f9
