### ISSUE TITLE
jasylibrary.js working directory is same as calling project

### ISSUE THREAD

**Issue by timmjd** [zynga/jasy#115]
if you have a jasyproject.py in /root/ and a jasylibrary.py in /root/foo/ and call a @share function from the jasyprojects.py it will be executed in /root/

Workaround in jasy/core/Sesssion.py

> parentDir = os.getcwd()
>    os.chdir(os.path.dirname(os.path.abspath(fileName)))
>    exec(compile(code, os.path.abspath(fileName), "exec"), {"share" : share})
>    os.chdir(parentDir)

to change the executing the library.

But this will not fix the @share function call: This is still called in the wrong directory context.

**Comment by swernerx** [comment]
I think this is the right behavior. It was designed this way. All code is executed in the main project's folder - aka the top-level project you are actually using. What is your use case for even requiring being executed in that folder? 

If you still need it might be better to just query for the path of the actual project which shares that method:

session.getProjectByName("myprojectname").getPath()

**Comment by timmjd** [comment]
For an example, if the library is used to generate code from within the library itself it needs to rely on a root directory of the library.

In the current design the root directory of the library always rely on the including project.

With the current design it is impossible to create reusable libraries that need to work on content from within the library:
- if you import a library by /external/foo or by /shared/external/foo it will result in different behavior due the root path will change.

So code that needs to generate some code inside the library
- process on file ./src/foo.bar and generate ./assets/something.net
  will not work if the library is included from within different root directories.

So there should be some way to get the root directory of the library.
Also the session object is invalid inside the @share function of the library.

**Comment by swernerx** [comment]
We'll add the session object to shared methods in jasylibrary.py files so that these have full access to the current environment. To change the working directory one could easily do a

os.chdir(session.getProjectByName("myprojectname").getPath())

while replacing "myprojectname" with the actual name of the project to switch to.
