### ISSUE TITLE
Windows install trouble

### ISSUE THREAD

**Issue by remotesynth** [zynga/jasy#118]
I am trying to install jasy on Windows but on the final step, running "pip-3.3 install jasy," fails. I get the error "cannot import name chardet2." Here is the full error detail from my console. Please let me know if you need additional info.

Downloading/unpacking requests>=0.13 (from jasy)
  Downloading requests-0.14.2.tar.gz (361kB): 361kB downloaded
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\brinaldi\appdata\local\temp\pip-build\requests\setup.py", l
ine 6, in <module>
        import requests
      File ".\requests__init__.py", line 52, in <module>
        from . import utils
      File ".\requests\utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File ".\requests\compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name chardet2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\brinaldi\appdata\local\temp\pip-build\requests\setup.py", line
6, in <module>

   import requests

  File ".\requests__init__.py", line 52, in <module>

   from . import utils

  File ".\requests\utils.py", line 22, in <module>

   from .compat import parse_http_list as _parse_list_header

  File ".\requests\compat.py", line 112, in <module>

   from .packages import chardet2 as chardet

ImportError: cannot import name chardet2

---

Command python setup.py egg_info failed with error code 1 in c:\users\brinaldi\a
ppdata\local\temp\pip-build\requests
Storing complete log in C:\Users\brinaldi\pip\pip.log

**Comment by dadicool** [comment]
There's this note on the Wiki :

`Warning: Installation of Jasy dependency requests is broken with version 0.14.2 in Python 3. Try install requests on your own and/or verify that the version is between 0.13 and 0.14.1 (pip install chardet2 requests==0.13 jasy). Sorry for the inconvenience.`

Can you try the suggested solution?

**Comment by remotesynth** [comment]
Thanks for your response. I tried the command you mention and received the identical error. I apologize if I seem dense but I am not clear on what is meant by "try install requests on your own."

**Comment by saschagoebel** [comment]
Have you tried installing chardet2 and requests before installing jasy?

`pip install chardet 2
pip install requests==0.13
pip install jasy`

**Comment by remotesynth** [comment]
Thank you. That works.

**Comment by remotesynth** [comment]
Actually, I spoke too soon. The install said it was successful but then when I try to run jasy it says:

Jasy requirement error: "requests"
- Version is NOT OK (needed: 0.14 installed: 0.13.0)
- Update to the newest version of requests using 'pip install --upgrade requests'

Trying to run that command leads to the same message as when trying to install jasy before:

C:\Users\brinaldi>pip install --upgrade requests
Downloading/unpacking requests from http://pypi.python.org/packages/source/r/req
uests/requests-0.14.2.tar.gz#md5=488508ba3e8270992ad5b3fb54d364ca
  Downloading requests-0.14.2.tar.gz (361kB): 361kB downloaded
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\brinaldi\appdata\local\temp\pip-build\requests\setup.py", l
ine 6, in <module>
        import requests
      File ".\requests__init__.py", line 52, in <module>
        from . import utils
      File ".\requests\utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File ".\requests\compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name chardet2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\brinaldi\appdata\local\temp\pip-build\requests\setup.py", line
6, in <module>

   import requests

  File ".\requests__init__.py", line 52, in <module>

   from . import utils

  File ".\requests\utils.py", line 22, in <module>

   from .compat import parse_http_list as _parse_list_header

  File ".\requests\compat.py", line 112, in <module>

   from .packages import chardet2 as chardet

ImportError: cannot import name chardet2

**Comment by saschagoebel** [comment]
Have you tried to completely uninstall all dependencies and make a clean install using the installation hints?

**Comment by remotesynth** [comment]
Tried that...no luck. The issue I keep having is, even if it installs without error by using requests version 0.13, when I try to run Jasy it says it needs version 0.14. the installation runs successfully, but then when I run Jasy, I get:

C:\Users\brinaldi>jasy
Jasy requirement error: "requests"
- Version is NOT OK (needed: 0.14 installed: 0.13.0)
- Update to the newest version of requests using 'pip install --upgrade requests

Upgrading requests to 0.14 works but then running Jasy gives me:

C:\Users\brinaldi>jasy

> > > ## INITIALIZING
> > > 
> > > Traceback (most recent call last):
> > >   File "C:\Python33\Scripts\jasy", line 235, in <module>
> > >    init()
> > >   File "C:\Python33\Scripts\jasy", line 177, in init
> > >    import jasy.env.Context as Context
> > >   File "C:\Python33\lib\site-packages\jasy\env\Context.py", line 23, in <module>

   from jasy.http.Server import Server
  File "C:\Python33\lib\site-packages\jasy\http\Server.py", line 6, in <module>
   import os, logging, base64, json, requests, cherrypy, locale
  File "C:\Python33\lib\site-packages\cherrypy-3.2.2-py3.3-win32.egg\cherrypy__
init__.py", line 82, in <module>
   from cherrypy import process
  File "C:\Python33\lib\site-packages\cherrypy-3.2.2-py3.3-win32.egg\cherrypy\pr
ocess__init__.py", line 14, in <module>
   from cherrypy.process import plugins, servers
  File "C:\Python33\lib\site-packages\cherrypy-3.2.2-py3.3-win32.egg\cherrypy\pr
ocess\plugins.py", line 424, in <module>
   class PerpetualTimer(threading._Timer):
AttributeError: 'module' object has no attribute '_Timer'

**Comment by saschagoebel** [comment]
Ok, now things get tricky.

Can you try the following:
- Uninstall Jasy & Dependencies
- Install as described with requests 0.13
- Open the file https://github.com/zynga/jasy/blob/master/jasy/core/Doctor.py in your local installation (C:\Python33\lib\site-packages\jasy\core\Doctor.py)
- Change the requests version from 0.14 to 0.13
- Run jasy

Sorry for the hassle!

**Comment by fbrandel** [comment]
I ran into the same problem when installing Jasy on OS X.

Even after downgrading to request 0.13 and fixing the dependency version, jasy returned an error:

```
File "/usr/local/lib/python3.3/site-packages/cherrypy/process/plugins.py", line 424, in <module>
class PerpetualTimer(threading._Timer):
AttributeError: 'module' object has no attribute '_Timer'
```

This led me to a python3.3 bug within CherryPy, described here: https://bitbucket.org/cherrypy/cherrypy/issue/1163/attributeerror-in-cherrypyprocessplugins

End of story: I installed CherryPy again using the Bitbucket source (not via pip) and it worked.

**Comment by remotesynth** [comment]
fbrandel is right. I did what you instructed but without either downloading the bitbucket source or modifying /cherrypy/process/plugins.py as instructed in the link he provided it still didn't work. However, once I did modify that file, I can call jasy and get the help menu.

**Comment by saschagoebel** [comment]
You modified the Doctor.py and then it worked?

**Comment by remotesynth** [comment]
No. I modified /cherrypy/process/plugins.py (the details are in the link fbrandel provided).

**Comment by saschagoebel** [comment]
Ok, got it. Thanks for the feedback!
