### ISSUE TITLE
Invalid version number when I call jasy from command line

### ISSUE THREAD

**Issue by northstream** [zynga/jasy#119]
Hello! I followed installation instruction for Windows, installed jasy using pip-3.3, but when I call jasy from command line (and expect to see help)  I receive ValueError: invalid version number '1.6rc1' in version.py line 143. It's in c:\Python33\lib\distutils

Could you please help me to solve this issue?

Thanks!

**Comment by saschagoebel** [comment]
Hi,

it looks like the described error is in distutils, not in Jasy. Could you please provide a stack trace of the error?

**Comment by northstream** [comment]
Sure.

Microsoft Windows XP [Version 5.1.2600](C) Copyright 1985-2001 Microsoft Corp.

Traceback (most recent call last):
  File "C:\Python33\Scripts\jasy", line 110, in <module>
    if not Doctor.doInitializationDoctor():
  File "C:\Python33\lib\site-packages\jasy\core\Doctor.py", line 155, in doIniti
alizationDoctor
    if not checkSingleInstallation(keys, versions, entry["packageName"], entry["
minVersion"], entry["installPath"], entry["updatePath"]):
  File "C:\Python33\lib\site-packages\jasy\core\Doctor.py", line 135, in checkSi
ngleInstallation
    if StrictVersion(versions[packageName.lower()]) < StrictVersion(minVersion):

  File "C:\Python33\lib\distutils\version.py", line 40, in **init**
    self.parse(vstring)
  File "C:\Python33\lib\distutils\version.py", line 143, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '1.6rc1'

**Comment by fschimmelpfennig** [comment]
Hi,
jasy requires some packages and checks at the beginning if all packages are installed in a jasy compatible version. Seems that jasy has a problem with analyzing the a package with version '1.6rc1'. Can you check out which of the required packages has got this version number and try to up-/downgrade to a non release candidate version?

This are the requirements for jasy:

```
    "packageName": "Pygments",
    "minVersion": "1.5",

    "packageName": "polib",
    "minVersion": "1.0.1",

    "packageName": "requests",
    "minVersion": "0.14",

    "packageName": "CherryPy",
    "minVersion": "3.2",

    "packageName": "PyYAML",
    "minVersion": "3.1",
```

**Comment by gibboj** [comment]
kgibbons$ pygmentize -V
Pygments version 1.6rc1, (c) 2006-2013 by Georg Brandl.
