### ISSUE TITLE
documentation insufficient for new users

### ISSUE THREAD

**Issue by lorinbeer** [zynga/jasy#2]
wiki provides a high level overview of jasy functionality, while code documentation is almost non-existent. Most functions/classes lack even one line docstrings.

Could use a lower level of documentation, such as specific examples of why/where we would use certain features. A small example project would be greatly appreciated.

**Comment by swernerx** [comment]
You are right. Making it usable for other users was not yet a focus. This is just a side project of mine - unfortunately. Could not give us a good roadmap for now. I like contributors though.

**Comment by swernerx** [comment]
Jasy will be an official Zynga project in the future. Development speed is pretty high at the moment and it's a focus to make it ready for broader usage.
