### ISSUE TITLE
urlPrefix of CDN-Url's wrong

### ISSUE THREAD

**Issue by fastner** [zynga/jasy#33]
If you run `asset.exportBuild(urlPrefix="https://example.com")` the resulting url of `core.io.Asset.toUri("test/test.png")` is `https:/example.com/test/test.png`. Note that there is only one slash after `https:`. This is due to calling `os.path.normpath` in core/Project.py inside `toRelativeUrl` method.

You can work around if you give an urlPrefix of "//example.com".

**Comment by swernerx** [comment]
Can you verify whether this is still an issue in 0.7.1?

**Comment by fastner** [comment]
Is fixed.
