### ISSUE TITLE
CamelCase not supported in jasy create

### ISSUE THREAD

**Issue by Zenwolf** [zynga/jasy#61]
When I use the create command with a CamelCase project name, it fails.

```
>>> CREATING PROJECT TESTAPP
-------------------------------------------------------------------------------
Invalid project name: TestApp
```

**Comment by dadicool** [comment]
The regex that defines admissible project names is : `validProjectName = re.compile(r"^[a-z][a-z0-9]*$")`

the projectName needs to be an admissible JS and Python namespace (so no `_` because JS doesn't like that). Not sure why uppercase isn't supported here.

**Comment by swernerx** [comment]
This check was added. It's a feature not a bug. It's about to only support project names which are widely useable in a lot of different code situations. It must be for example useable for:
- JS Packages / Namespaces
- Filesystem Names
- Case Insensitive Areas
- Python Code
- Template Languages
