### ISSUE TITLE
Root directory for the server

### ISSUE THREAD

**Issue by timmjd** [zynga/jasy#63]
Current implementation uses the jasy root project also as root for the server.
Perfect would be something like "DocumentRoot" like it is used in Apache.

**Comment by dadicool** [comment]
This is doable today with the embedded jasy server.

Project layout example :

```
/assets
/web/jasyproject.yaml
/web/jasyscript.yaml
/web/source/class/*.js
```

The usual workflow is to have a jasy task : `server` and run it in the `/web` folder. If your js files want to reference assets in the `/assets` folder, you can't just rely on URL paths to access them and you need a "rewrite rule". This is where the `routes` parameter to the serve method in jasy comes in handy.

You should define your jasy server task as follows :

```
@task
def server():
    """Start HTTP server"""

    serve(routes = {
    'assets' : {
        'root' : '../assets',
        'debug' : True
        }
    })
```

This will make requests to : `http://localhost/assets/foo.png` to be served from the : `/assets/foo.png` file in the filesystem.

**Comment by swernerx** [comment]
I think the last tip basically solves the issue. Reopen if you think different.
