### ISSUE TITLE
For Dumb Developers, please provide a link in the Walkthrough on how to install pip-3.2

### ISSUE THREAD

**Issue by mpelham** [zynga/jasy#73]
Took me about  20 minutes of googling to install pip-3.2 explicitly.

http://stackoverflow.com/questions/11268501/how-to-use-pip-with-python-3-x-besides-python-2-x

**Comment by swernerx** [comment]
PIP-3.2 will be auto-installed with Homebrew. Just follow the up-to-date installation guides :)
