### ISSUE TITLE
jasy create --version requires a different format than other arguments

### ISSUE THREAD

**Issue by Zenwolf** [zynga/jasy#75]
For some reason, the --version argument requires a different format than the --name and --origin arguments, making it confusing for users:

```
Doesn't work: --version refs/tags/0.0.4

Works:        --version=refs/tags/0.0.4
```

Compare to --origin path/to/my/repo

**Comment by swernerx** [comment]
Might be related to the slashes. There is no hard-coded difference in here otherwise.

BTW: You can alternatively use the pure version as long as it's identifyable as a version number (0.0.4 is fine)

**Comment by swernerx** [comment]
Ah sorry, have seen that you mentioned that the same works for origin with slashes. In fact it also might be related to the built-in --version support in Jasy which prints out the Jasy version. Not sure. Will have to debug that.

**Comment by swernerx** [comment]
Fixed that in jasy08 branch. Renamed flag to --origin-version.
